# Stubs for django.db.models (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.models.aggregates import *
from django.db.models.fields import *
from django.db.models.fields.files import *
from django.db.models.fields.related import *
from django.db.models.base import *
from django.db.models.query_utils import *
from django.db.models.manager import *
from django.db.models.deletion import *

def permalink(func): ...
