# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 23:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='HomecomingCourtNomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('female_nominee',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homecoming_court_female_nominations',
                                   to=settings.AUTH_USER_MODEL)),
                ('male_nominee',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homecoming_court_male_nominations',
                                   to=settings.AUTH_USER_MODEL)),
                ('voter',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homecoming_court_nominations',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
