# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-24 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('context', models.CharField(choices=[('dashboard', 'dashboard'), ('login', 'login'), ('eighth_signup', 'eighth_signup')], max_length=20)),
                ('announcement_html', models.CharField(help_text='The HTML for the feature announcement (do NOT allow untrusted content)', max_length=1024)),
                ('users_dismissed', models.ManyToManyField(blank=True, related_name='feature_announcements_dismissed', to=settings.AUTH_USER_MODEL)),
                ('users_seen', models.ManyToManyField(blank=True, related_name='feature_announcements_seen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
