# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-17 19:03
from __future__ import unicode_literals

import datetime

from django.db import migrations

feature_announcements = [
    {
        "activation_date": datetime.date(2019, 11, 17),
        "expiration_date": datetime.date(2019, 11, 23),
        "context": "dashboard",
        "announcement_html": 'New: Ion now has a <a href="/sessions">session management page</a> where you can "trust" sessions to stay logged in longer.',
    }
]


def add_feature_announcements(apps, schema_editor):
    FeatureAnnouncement = apps.get_model("features", "FeatureAnnouncement")
    for data in feature_announcements:
        FeatureAnnouncement.objects.get_or_create(**data)


def remove_feature_announcements(apps, schema_editor):
    FeatureAnnouncement = apps.get_model("features", "FeatureAnnouncement")
    for data in feature_announcements:
        FeatureAnnouncement.objects.filter(**data).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_feature_announcements, remove_feature_announcements),
    ]
