# Generated by Django 3.2.15 on 2022-11-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_alter_cslapplication_client_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cslapplication',
            name='sanctioned',
            field=models.BooleanField(default=False, help_text='Whether this application is sanctioned by the tjCSL.'),
        ),
        migrations.AlterField(
            model_name='cslapplication',
            name='skip_authorization',
            field=models.BooleanField(default=False, help_text='Set this to true to skip the authorization page for this application. This should be true for sanctioned CSL applications.'),
        ),
    ]
