# Generated by Django 3.2.15 on 2022-12-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20221130_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cslapplication',
            name='skip_authorization',
            field=models.BooleanField(default=False, help_text='Set this to true to skip the authorization page for this application. This will automatically be set to true upon save if this application marked as sanctioned by the CSL.'),
        ),
    ]
