# Generated by Django 3.2.15 on 2022-12-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_auto_20221219_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cslapplication',
            name='sanctioned_but_do_not_skip_authorization',
            field=models.BooleanField(default=False, help_text='Set to true if this application is sanctioned but you do NOT want to skip the authorization page for this application. Overrides automatically skipping authorization for sanctioned applications.'),
        ),
        migrations.AlterField(
            model_name='cslapplication',
            name='skip_authorization',
            field=models.BooleanField(default=False, help_text='Skip the authorization page for this application. This will automatically be set to true upon save if this application is marked as sanctioned by the CSL.'),
        ),
    ]
