# Generated by Django 3.2.15 on 2022-12-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_auto_20221219_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cslapplication',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
