# Generated by Django 3.2.20 on 2024-03-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0008_auto_20221224_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='cslapplication',
            name='post_logout_redirect_uris',
            field=models.TextField(blank=True, help_text='Allowed Post Logout URIs list, space separated'),
        ),
    ]
