# Generated by Django 3.2.25 on 2024-09-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0009_cslapplication_post_logout_redirect_uris'),
    ]

    operations = [
        migrations.AddField(
            model_name='cslapplication',
            name='allowed_origins',
            field=models.TextField(blank=True, default='', help_text='Allowed origins list to enable CORS, space separated'),
        ),
        migrations.AddField(
            model_name='cslapplication',
            name='hash_client_secret',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cslapplication',
            name='post_logout_redirect_uris',
            field=models.TextField(blank=True, default='', help_text='Allowed Post Logout URIs list, space separated'),
        ),
    ]
