# Generated by Django 5.2.4 on 2025-07-13 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0009_cslapplication_post_logout_redirect_uris'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cslapplication',
            name='allowed_origins',
            field=models.TextField(blank=True, default='', help_text='Allowed origins list to enable CORS, space separated'),
        ),
        migrations.AddField(
            model_name='cslapplication',
            name='hash_client_secret',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cslapplication',
            name='post_logout_redirect_uris',
            field=models.TextField(blank=True, default='', help_text='Allowed Post Logout URIs list, space separated'),
        ),
        migrations.AlterField(
            model_name='cslapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
