# Generated by Django 5.2.4 on 2025-09-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0010_cslapplication_allowed_origins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cslapplication',
            name='algorithm',
            field=models.CharField(blank=True, choices=[('', 'No OIDC support'), ('RS256', 'RSA with SHA-2 256')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='cslapplication',
            name='authorization_grant_type',
            field=models.CharField(choices=[('authorization-code', 'Authorization code'), ('client-credentials', 'Client credentials'), ('openid-hybrid', 'OpenID connect hybrid')], max_length=32),
        ),
    ]
