# Generated by Django 5.2.4 on 2025-09-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0011_alter_cslapplication_algorithm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cslapplication',
            name='oidc_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cslapplication',
            name='authorization_grant_type',
            field=models.CharField(choices=[('authorization-code', 'Authorization code'), ('client-credentials', 'Client credentials')], max_length=32),
        ),
    ]
