# Stubs for maintenancemode.conf (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from appconf import AppConf

class MaintenanceSettings(AppConf):
    IGNORE_URLS = ...  # type: Any
    LOCKFILE_PATH = ...  # type: Any
    MODE = ...  # type: Any
    class Meta:
        prefix = ...  # type: Any
        holder = ...  # type: Any
