# Stubs for maintenancemode.middleware (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from . import utils as maintenance

IGNORE_URLS = ...  # type: Any

class MaintenanceModeMiddleware:
    def process_request(self, request): ...
