# Stubs for corsheaders.defaults (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

default_headers = ...  # type: Any
CORS_ALLOW_HEADERS = ...  # type: Any
default_methods = ...  # type: Any
CORS_ALLOW_METHODS = ...  # type: Any
CORS_ALLOW_CREDENTIALS = ...  # type: Any
CORS_PREFLIGHT_MAX_AGE = ...  # type: Any
CORS_ORIGIN_ALLOW_ALL = ...  # type: Any
CORS_ORIGIN_WHITELIST = ...  # type: Any
CORS_ORIGIN_REGEX_WHITELIST = ...  # type: Any
CORS_EXPOSE_HEADERS = ...  # type: Any
CORS_URLS_REGEX = ...  # type: Any
CORS_MODEL = ...  # type: Any
CORS_REPLACE_HTTPS_REFERER = ...  # type: Any
