# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-12 23:42
from __future__ import unicode_literals

from django.db import migrations


def remove_duplicate_trustedsessions(apps, schema_editor):
    TrustedSession = apps.get_model("sessionmgmt", "TrustedSession")
    for tsession in TrustedSession.objects.all():
        if TrustedSession.objects.filter(user=tsession.user, session_key=tsession.session_key).exclude(pk=tsession.pk).exists():
            tsession.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('sessionmgmt', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_trustedsessions, lambda *args, **kwargs: None),
    ]
