# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-12 23:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessionmgmt', '0002_auto_20191012_1942'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trustedsession',
            unique_together=set([('user', 'session_key')]),
        ),
    ]
