# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-14 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionmgmt', '0003_auto_20191012_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustedsession',
            name='device_type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('computer', 'Computer'), ('unknown', 'Unknown type')], max_length=8),
        ),
    ]
