from .views import APIView
class CreateAPIView(APIView): ...
class ListAPIView(APIView): ...
class ListCreateAPIView(APIView): ...
class RetrieveAPIView(APIView): ...
class RetrieveUpdateDestroyAPIView(APIView): ...
