class ModelSerializer:
  # FIXME: actually figure out args
  def __init__(self, *args, **kwargs): ...
class HyperlinkedModelSerializer: ...
class StringRelatedField: ...
class HyperlinkedIdentityField:
  # FIXME: actually figure out args
  def __init__(self, *args, **kwargs): ...
