# Generated by Django 3.2.20 on 2024-03-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('enrichment', '0002_alter_enrichmentactivity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmentactivity',
            name='groups_allowed',
            field=models.ManyToManyField(blank=True, related_name='allowed_enrichments_set', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='enrichmentactivity',
            name='groups_blacklisted',
            field=models.ManyToManyField(blank=True, related_name='blacklisted_enrichments_set', to='auth.Group'),
        ),
    ]
