# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('users', '0007_user_receive_schedule_notifications')]

    operations = [migrations.AddField(
        model_name='user',
        name='_student_id',
        field=models.PositiveIntegerField(null=True),
    )]
