# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('users', '0008_user__student_id')]

    operations = [migrations.AddField(
        model_name='user',
        name='user_locked',
        field=models.BooleanField(default=False),
    )]
