# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('users', '0009_user_user_locked')]

    operations = [
        migrations.AddField(model_name='user', name='gender_cached', field=models.NullBooleanField()),
        migrations.AddField(model_name='user', name='object_class_cached', field=models.CharField(max_length=15, null=True)),
    ]
