# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_user_locked'),
    ]

    operations = [
        migrations.RenameField('User', 'is_superuser', '_is_superuser')
    ]
