# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('users', '0010_auto_20161016_1343')]

    operations = [
        migrations.CreateModel(
            name='UserCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1, null=True)),
                ('objectClass', models.CharField(max_length=15, null=True)),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.RemoveField(model_name='user', name='gender_cached'),
        migrations.RemoveField(model_name='user', name='object_class_cached'),
        migrations.AddField(model_name='user', name='cache',
                            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.UserCache')),
    ]
