# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_rename_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
