# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('users', '0012_auto_20161016_1510')]

    operations = [migrations.AlterField(model_name='usercache', name='gender', field=models.NullBooleanField())]
