# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('users', '0013_auto_20161016_1525')]

    operations = [
        migrations.AddField(model_name='usercache', name='grade_number', field=models.PositiveIntegerField(null=True)),
        migrations.AddField(model_name='usercache', name='graduation_year', field=models.PositiveIntegerField(null=True)),
    ]
