# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20170731_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='grade_number',
            field=models.IntegerField(choices=[(9, 'freshman'), (10, 'sophomore'), (11, 'junior'), (12, 'senior'), (13, 'staff')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='counselor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade_number',
            field=models.IntegerField(choices=[(9, 'freshman'), (10, 'sophomore'), (11, 'junior'), (12, 'senior'), (13, 'staff')], default=9),
        ),
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together=set([('user', 'number')]),
        ),
    ]
