# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20170803_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grade_number',
        ),
    ]
