# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 01:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20170805_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_birthday', models.DateField(null=True)),
                ('self_show_pictures', models.BooleanField(default=False)),
                ('parent_show_pictures', models.BooleanField(default=False)),
                ('self_show_address', models.BooleanField(default=False)),
                ('parent_show_address', models.BooleanField(default=False)),
                ('self_show_telephone', models.BooleanField(default=False)),
                ('parent_show_telephone', models.BooleanField(default=False)),
                ('self_show_birthday', models.BooleanField(default=False)),
                ('parent_show_birthday', models.BooleanField(default=False)),
                ('self_show_eighth', models.BooleanField(default=False)),
                ('parent_show_eighth', models.BooleanField(default=False)),
                ('_address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Address')),
            ],
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='number',
            new_name='_number',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='binary',
            new_name='_binary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='_student_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_show_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_show_birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_show_eighth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_show_pictures',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_show_telephone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='self_show_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='self_show_birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='self_show_eighth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='self_show_pictures',
        ),
        migrations.RemoveField(
            model_name='user',
            name='self_show_telephone',
        ),
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together=set([('user', '_number')]),
        ),
        migrations.AddField(
            model_name='userproperties',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
