# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20170806_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('counselor', 'Counselor'),
                                            ('user', 'Attendance-Only User'), ('simple_user', 'Simple User'),
                                            ('tjstar_presenter', 'tjStar Presenter'), ('alum', 'Alumnus'), ('service', 'Service Account')],
                                   default='student', max_length=30),
        ),
    ]
