# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20170817_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_title', models.CharField(max_length=50)),
                ('course_id', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=16)),
                ('period', models.IntegerField()),
                ('section_id', models.CharField(max_length=16, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userproperties',
            name='parent_show_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userproperties',
            name='self_show_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userproperties',
            name='_schedule',
            field=models.ManyToManyField(related_name='_students', to='users.Section'),
        ),
    ]
