# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20170823_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='_quarters',
            field=models.CharField(default='1234', max_length=4),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='users.Course'),
        ),
    ]
