# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20170824_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='short_title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.RemoveField(
            model_name='section',
            name='_quarters',
        ),
        migrations.AddField(
            model_name='section',
            name='sem',
            field=models.CharField(default='YR', max_length=2),
            preserve_default=False,
        ),
    ]
