# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-01 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20170825_1610'),
        ('users', '0015_user_bus_route'),
    ]

    operations = []
