# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-15 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_merge_20171231_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name', 'course_id')},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('section_id', 'period')},
        ),
    ]
