# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20190715_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDarkModeProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_dark_mode_unlocked', models.BooleanField(default=False)),
                ('dark_mode_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dark_mode_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
