# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-16 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_user_last_global_logout_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdarkmodeproperties',
            name='_dark_mode_unlocked',
        ),
    ]
