# Generated by Django 3.2.15 on 2022-12-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20221224_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_and_api_access',
            field=models.BooleanField(default=True, help_text='Whether the user can create OAuth applications and access the API.'),
        ),
    ]
