# Generated by Django 3.2.17 on 2023-03-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_user_enable_april_fools'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seen_april_fools',
            field=models.BooleanField(default=False),
        ),
    ]
