# Generated by Django 5.2.4 on 2025-10-18 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_user_seen_april_fools'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserThemeProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_choice', models.CharField(default='light_theme', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
