# Generated by Django 3.2.25 on 2025-05-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_user_seen_april_fools'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
