# Generated by Django 5.2.4 on 2025-09-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_user_seen_april_fools'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_archived',
            field=models.BooleanField(default=False),
        ),
    ]
