# Generated by Django 3.2.25 on 2025-05-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0002_auto_20160828_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
