# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('polls', '0003_auto_20151117_2139')]

    operations = [migrations.AddField(
        model_name='answer',
        name='answer',
        field=models.CharField(max_length=10000, null=True),
    )]
