# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('polls', '0005_question_max_choices')]

    operations = [migrations.AlterModelOptions(
        name='choice',
        options={'ordering': ['num']},
    )]
