# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20160828_2058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerVotes',
            new_name='AnswerVote',
        ),
    ]
