# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-17 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170425_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
    ]
