# Generated by Django 3.2.12 on 2022-05-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_poll_is_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('STD', 'Standard'), ('ELC', 'Election'), ('RAN', 'Rank choice'), ('APP', 'Approval'), ('SAP', 'Split approval'), ('FRE', 'Free response'), ('SRE', 'Short response'), ('STO', 'Standard other')], default='STD', max_length=3),
        ),
    ]
