# Generated by Django 3.2.15 on 2022-10-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20220502_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_election',
            field=models.BooleanField(default=False),
        ),
    ]
