# Generated by Django 3.2.17 on 2023-05-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_poll_is_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_randomized',
            field=models.BooleanField(default=False),
        ),
    ]
