# Generated by Django 3.2.18 on 2023-05-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_poll_is_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='other_vote',
            field=models.BooleanField(default=False),
        ),
    ]
