# Generated by Django 5.2.11 on 2026-05-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_answer_other_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_randomized',
            field=models.BooleanField(default=False),
        ),
    ]
