# Stubs for django.core.files.images (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.core.files import File

class ImageFile(File):
    width = ... # type: Any
    height = ... # type: Any

def get_image_dimensions(file_or_path, close=False): ...
