# Stubs for django.core.files.utils (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class FileProxyMixin:
    encoding = ... # type: Any
    fileno = ... # type: Any
    flush = ... # type: Any
    isatty = ... # type: Any
    newlines = ... # type: Any
    read = ... # type: Any
    readinto = ... # type: Any
    readline = ... # type: Any
    readlines = ... # type: Any
    seek = ... # type: Any
    softspace = ... # type: Any
    tell = ... # type: Any
    truncate = ... # type: Any
    write = ... # type: Any
    writelines = ... # type: Any
    xreadlines = ... # type: Any
    seekable = ... # type: Any
    def __iter__(self): ...
