# Stubs for bleach (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def clean(text, tags: Any = ..., attributes: Any = ..., styles: Any = ..., protocols: Any = ..., strip: bool = ..., strip_comments: bool = ...): ...
def linkify(text, callbacks: Any = ..., skip_tags: Optional[Any] = ..., parse_email: bool = ...): ...
