# Stubs for setuptools (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class PackageFinder:
    @classmethod
    def find(cls, where: str = ..., exclude: Any = ..., include: Any = ...): ...

class PEP420PackageFinder(PackageFinder): ...

find_packages = ...  # type: Any
setup = ...  # type: Any
