# Stubs for paramiko (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from paramiko.ssh_exception import SSHException as SSHException, PasswordRequiredException as PasswordRequiredException, BadAuthenticationType as BadAuthenticationType, ChannelException as ChannelException, BadHostKeyException as BadHostKeyException, AuthenticationException as AuthenticationException, ProxyCommandFailure as ProxyCommandFailure
