# Stubs for paramiko.config (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

SSH_PORT = ... # type: Any

class SSHConfig:
    SETTINGS_REGEX = ... # type: Any
    def __init__(self): ...
    def parse(self, file_obj): ...
    def lookup(self, hostname): ...
    def get_hostnames(self): ...

class LazyFqdn:
    fqdn = ... # type: Any
    config = ... # type: Any
    host = ... # type: Any
    def __init__(self, config, host=None): ...
