# Stubs for paramiko.proxy (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from shlex import split as shlsplit
from paramiko.util import ClosingContextManager

class ProxyCommand(ClosingContextManager):
    cmd = ... # type: Any
    process = ... # type: Any
    timeout = ... # type: Any
    buffer = ... # type: Any
    def __init__(self, command_line): ...
    def send(self, content): ...
    def recv(self, size): ...
    def close(self): ...
    def settimeout(self, timeout): ...
