# Stubs for paramiko.sftp_attr (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class SFTPAttributes:
    FLAG_SIZE = ... # type: Any
    FLAG_UIDGID = ... # type: Any
    FLAG_PERMISSIONS = ... # type: Any
    FLAG_AMTIME = ... # type: Any
    FLAG_EXTENDED = ... # type: Any
    st_size = ... # type: Any
    st_uid = ... # type: Any
    st_gid = ... # type: Any
    st_mode = ... # type: Any
    st_atime = ... # type: Any
    st_mtime = ... # type: Any
    attr = ... # type: Any
    def __init__(self): ...
    @classmethod
    def from_stat(cls, obj, filename=None): ...
    def asbytes(self): ...
