# Stubs for paramiko.sftp (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

CMD_INIT = ... # type: Any
CMD_VERSION = ... # type: Any
CMD_OPEN = ... # type: Any
CMD_CLOSE = ... # type: Any
CMD_READ = ... # type: Any
CMD_WRITE = ... # type: Any
CMD_LSTAT = ... # type: Any
CMD_FSTAT = ... # type: Any
CMD_SETSTAT = ... # type: Any
CMD_FSETSTAT = ... # type: Any
CMD_OPENDIR = ... # type: Any
CMD_READDIR = ... # type: Any
CMD_REMOVE = ... # type: Any
CMD_MKDIR = ... # type: Any
CMD_RMDIR = ... # type: Any
CMD_REALPATH = ... # type: Any
CMD_STAT = ... # type: Any
CMD_RENAME = ... # type: Any
CMD_READLINK = ... # type: Any
CMD_SYMLINK = ... # type: Any
CMD_STATUS = ... # type: Any
CMD_HANDLE = ... # type: Any
CMD_DATA = ... # type: Any
CMD_NAME = ... # type: Any
CMD_ATTRS = ... # type: Any
CMD_EXTENDED = ... # type: Any
CMD_EXTENDED_REPLY = ... # type: Any
SFTP_OK = ... # type: Any
SFTP_EOF = ... # type: Any
SFTP_NO_SUCH_FILE = ... # type: Any
SFTP_PERMISSION_DENIED = ... # type: Any
SFTP_FAILURE = ... # type: Any
SFTP_BAD_MESSAGE = ... # type: Any
SFTP_NO_CONNECTION = ... # type: Any
SFTP_CONNECTION_LOST = ... # type: Any
SFTP_OP_UNSUPPORTED = ... # type: Any
SFTP_DESC = ... # type: Any
SFTP_FLAG_READ = ... # type: Any
SFTP_FLAG_WRITE = ... # type: Any
SFTP_FLAG_APPEND = ... # type: Any
SFTP_FLAG_CREATE = ... # type: Any
SFTP_FLAG_TRUNC = ... # type: Any
SFTP_FLAG_EXCL = ... # type: Any
CMD_NAMES = ... # type: Any

class SFTPError(Exception): ...

class BaseSFTP:
    logger = ... # type: Any
    sock = ... # type: Any
    ultra_debug = ... # type: Any
    def __init__(self): ...
