# Stubs for paramiko.sftp_server (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from paramiko.sftp import BaseSFTP
from paramiko.server import SubsystemHandler

class SFTPServer(BaseSFTP, SubsystemHandler):
    logger = ... # type: Any
    ultra_debug = ... # type: Any
    next_handle = ... # type: Any
    file_table = ... # type: Any
    folder_table = ... # type: Any
    server = ... # type: Any
    def __init__(self, channel, name, server, sftp_si=..., *largs, **kwargs): ...
    sock = ... # type: Any
    def start_subsystem(self, name, transport, channel): ...
    def finish_subsystem(self): ...
    @staticmethod
    def convert_errno(e): ...
    @staticmethod
    def set_file_attr(filename, attr): ...
