class PageBreak: ...
class Paragraph:
  # FIXME: figure out args
  def __init__(self, *args, **kwargs): ...
class SimpleDocTemplate:
  # FIXME: figure out args
  def __init__(self, *args, **kwargs): ...
class Spacer:
  # FIXME: figure out args
  def __init__(self, *args, **kwargs): ...
class Table:
  # FIXME: figure out args
  def __init__(self, *args, **kwargs): ...
class TableStyle:
  # FIXME: figure out args
  def __init__(self, *args, **kwargs): ...
