# Generated by Django 3.2.15 on 2022-09-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('url', models.CharField(blank=True, max_length=2048)),
                ('available_to_all', models.BooleanField(default=True)),
                ('groups_visible', models.ManyToManyField(blank=True, to='auth.Group')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
