# Generated by Django 3.2.15 on 2022-09-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cslapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='image_url',
            field=models.CharField(blank=True, max_length=2097152),
        ),
    ]
