# Generated by Django 3.2.15 on 2022-09-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cslapps', '0002_app_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='icon',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
