# Generated by Django 3.2.15 on 2022-09-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cslapps', '0003_app_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='icon',
            new_name='html_icon',
        ),
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
