# Generated by Django 3.2.15 on 2022-09-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cslapps', '0004_auto_20220903_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
