# Generated by Django 3.2.15 on 2022-09-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cslapps', '0005_alter_app_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='auth_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='image_url',
            field=models.URLField(blank=True, max_length=2097152),
        ),
        migrations.AlterField(
            model_name='app',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
