# Generated by Django 3.2.20 on 2024-03-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cslapps', '0009_app_oauth_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='image_url',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
