# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('signage', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='status',
            field=models.CharField(choices=[('auto', 'Auto'), ('eighth', 'Eighth Period'), ('schedule', 'Bell Schedule'),
                                            ('status', 'Schedule/Clock'), ('url', 'Custom URL')], default='auto', max_length=10),
        ),
    ]
