# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('signage', '0004_auto_20160212_1121')]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='use_header',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sign',
            name='status',
            field=models.CharField(choices=[('auto', 'Auto - Schedule/Eighth'), ('autourl', 'Auto - URL/Eighth'), ('eighth', 'Eighth Period'),
                                            ('schedule', 'Bell Schedule'), ('status', 'Schedule/Clock'), ('touch', 'Touch Signage'),
                                            ('url', 'Custom URL')], default='auto', max_length=10),
        ),
    ]
