# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('signage', '0005_auto_20160303_1409')]

    operations = [migrations.AddField(
        model_name='sign',
        name='zoom',
        field=models.IntegerField(default=3),
    )]
