# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('signage', '0007_sign_landscape')]

    operations = [migrations.AddField(
        model_name='sign',
        name='map_location',
        field=models.CharField(blank=True, max_length=20, null=True),
    )]
