# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0008_sign_map_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe', models.BooleanField(default=False)),
                ('template', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('button', models.CharField(blank=True, max_length=30, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='sign',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='url',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='use_frameset',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='use_header',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='zoom',
        ),
        migrations.AddField(
            model_name='sign',
            name='default_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_unused_2', to='signage.Page'),
        ),
        migrations.AddField(
            model_name='sign',
            name='lock_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_unused_1', to='signage.Page'),
        ),
        migrations.AddField(
            model_name='sign',
            name='pages',
            field=models.ManyToManyField(to='signage.Page'),
        ),
    ]
