# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0009_auto_20180327_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='img_path',
            field=models.CharField(default='https://c1.staticflickr.com/5/4331/36927945575_c2c09e44db_k.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='sign',
            name='pages',
            field=models.ManyToManyField(related_name='signs', to='signage.Page'),
        ),
    ]
