# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0010_auto_20180327_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sandbox',
            field=models.BooleanField(default=True),
        ),
    ]
