# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0011_page_sandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='function',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='naitian.org', max_length=50),
            preserve_default=False,
        ),
    ]
