# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0012_auto_20180327_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='button',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
