# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0013_auto_20180329_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='strip_links',
            field=models.BooleanField(default=True),
        ),
    ]
