# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-22 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0014_page_strip_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='img_path',
            field=models.CharField(default='https://c1.staticflickr.com/5/4331/36927945575_c2c09e44db_k.jpg', max_length=250),
        ),
    ]
