# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0015_auto_20180422_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='day_end_switch_minutes',
            field=models.IntegerField(default=5, help_text='Switch pages this many minutes before the end of the day'),
        ),
        migrations.AddField(
            model_name='sign',
            name='day_end_switch_page',
            field=models.ForeignKey(blank=True, help_text='Switch to this page near the end of the day', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='signage.Page'),
        ),
    ]
