# Generated by Django 2.2.9 on 2020-01-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0016_auto_20191210_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='latest_heartbeat_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
