# Generated by Django 3.2.17 on 2023-04-23 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0017_sign_latest_heartbeat_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='sign',
            name='custom_switch_page',
            field=models.ForeignKey(blank=True, help_text='Switch to this page at the custom switch time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_page_signs', to='signage.page'),
        ),
        migrations.AddField(
            model_name='sign',
            name='custom_switch_time',
            field=models.DateTimeField(blank=True, help_text='Switch to a custom page at this time', null=True),
        ),
        migrations.AlterField(
            model_name='sign',
            name='default_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_signs', to='signage.page'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='lock_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_signs', to='signage.page'),
        ),
    ]
