# Generated by Django 3.2.17 on 2023-04-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0018_auto_20230422_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='custom_switch_time',
            field=models.TimeField(blank=True, help_text='Switch to the custom page at this time', null=True),
        ),
    ]
