# Generated by Django 3.2.17 on 2023-04-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0019_alter_sign_custom_switch_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='custom_switch_page_lock',
            field=models.BooleanField(default=False, help_text='Lock the custom page when switching to it'),
        ),
    ]
