# Stubs for django.views.decorators.http (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

conditional_page = ...  # type: Any
logger = ...  # type: Any

def require_http_methods(request_method_list): ...

require_GET = ...  # type: Any
require_POST = ...  # type: Any
require_safe = ...  # type: Any

def condition(etag_func: Optional[Any] = ..., last_modified_func: Optional[Any] = ...): ...
def etag(etag_func): ...
def last_modified(last_modified_func): ...
