from django.db.models.manager import Manager
class Group: ...
class AbstractBaseUser:
  # FIXME: actually figure out args
  def __init__(self, *args, **kwargs): ...
class AnonymousUser: ...
class PermissionsMixin: ...
class UserManager(Manager): ...
class GroupManager(Manager): ...
