# Generated by Django 3.2.25 on 2025-05-19 19:27

from django.db import migrations, models
import datetime
from ..models import shift_time
from ....settings.__init__ import ATTENDANCE_CODE_BUFFER

def populate_eighth_auto_fields(apps, schema_editor):
    DayType = apps.get_model('schedule', 'DayType')
    for obj in DayType.objects.all():
        earliest = None
        latest = None
        for blk in obj.blocks.all():
            name = blk.name
            if name is None:
                continue
            if "8" in name:
                start = datetime.time(hour=blk.start.hour, minute=blk.start.minute)
                end = datetime.time(hour=blk.end.hour, minute=blk.end.minute)
                if earliest is None or start <= earliest:
                    earliest = start
                if latest is None or end >= latest:
                    latest = end
        if earliest is None or latest is None:
            obj.eighth_auto_open = datetime.time(11, 59, 59)
            obj.eighth_auto_close = datetime.time(0,0,0)
        else:
            obj.eighth_auto_open = shift_time(earliest, -ATTENDANCE_CODE_BUFFER)
            obj.eighth_auto_close = shift_time(latest, ATTENDANCE_CODE_BUFFER)
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_day_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytype',
            name='eighth_auto_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daytype',
            name='eighth_auto_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RunPython(populate_eighth_auto_fields, reverse_code=migrations.RunPython.noop),
    ]
