# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0029_auto_20150724_1530'),
        ('eighth', '0035_eighthactivity_blacklist'),
    ]
