# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0036_eighthscheduledactivity_administrative'),
        ('eighth', '0037_auto_20160307_2342'),
    ]
