# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('eighth', '0038_merge')]

    operations = [
        migrations.AddField(
            model_name='eighthscheduledactivity',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eighthscheduledactivity',
            name='sticky',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaleighthscheduledactivity',
            name='administrative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaleighthscheduledactivity',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaleighthscheduledactivity',
            name='sticky',
            field=models.BooleanField(default=False),
        ),
    ]
