# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('eighth', '0039_auto_20160322_1013')]

    operations = [
        migrations.AddField(
            model_name='eighthscheduledactivity',
            name='both_blocks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaleighthscheduledactivity',
            name='both_blocks',
            field=models.BooleanField(default=False),
        ),
    ]
