# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('eighth', '0040_auto_20160515_1851')]

    operations = [
        migrations.AddField(
            model_name='eighthscheduledactivity',
            name='archived_member_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaleighthscheduledactivity',
            name='archived_member_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
