# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-18 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0052_auto_20170329_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eighthactivity',
            name='finance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaleighthactivity',
            name='finance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
