# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0053_auto_20170518_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaleighthactivity',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaleighthblock',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaleighthroom',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaleighthscheduledactivity',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaleighthsignup',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaleighthsponsor',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
