# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0054_auto_20170706_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='EighthActivitySimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True, null=True)),
                ('count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eighthactivity',
            name='similarities',
            field=models.ManyToManyField(blank=True, related_name='activity_set', to='eighth.EighthActivitySimilarity'),
        ),
    ]
