# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0055_auto_20171003_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='eighthactivitysimilarity',
            name='true_count',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
