# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0056_eighthactivitysimilarity_true_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eighthactivitysimilarity',
            name='true_count',
        ),
        migrations.AddField(
            model_name='eighthactivitysimilarity',
            name='weighted',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
