# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0057_auto_20171005_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='eighthroom',
            name='available_for_eighth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaleighthroom',
            name='available_for_eighth',
            field=models.BooleanField(default=True),
        ),
    ]
