# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-26 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eighth', '0058_auto_20171117_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='eighthsponsor',
            name='full_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaleighthsponsor',
            name='full_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='eighthsponsor',
            unique_together=set([('first_name', 'last_name', 'user', 'online_attendance', 'full_time')]),
        ),
    ]
