# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-26 22:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eighth', '0059_auto_20180726_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='eighthsponsor',
            name='department',
            field=models.CharField(choices=[('general', 'General'), ('math_cs', 'Math/CS'), ('english', 'English'), ('social_studies', 'Social Studies'), ('fine_arts', 'Fine Arts'), ('health_pe', 'Health/PE'), ('scitech', 'Science/Technology')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaleighthsponsor',
            name='department',
            field=models.CharField(choices=[('general', 'General'), ('math_cs', 'Math/CS'), ('english', 'English'), ('social_studies', 'Social Studies'), ('fine_arts', 'Fine Arts'), ('health_pe', 'Health/PE'), ('scitech', 'Science/Technology')], default='general', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='eighthsponsor',
            unique_together=set([('first_name', 'last_name', 'user', 'online_attendance', 'full_time', 'department')]),
        ),
    ]
