# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 03:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0060_auto_20180726_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eighthactivity',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='historicaleighthactivity',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
