# Generated by Django 2.2.9 on 2020-01-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0061_auto_20191215_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eighthactivity',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='eighthsignup',
            name='absence_acknowledged',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='eighthsignup',
            name='absence_emailed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='eighthsignup',
            name='archived_was_absent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='eighthsignup',
            name='pass_accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='eighthsignup',
            name='was_absent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicaleighthactivity',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicaleighthsignup',
            name='absence_acknowledged',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicaleighthsignup',
            name='absence_emailed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicaleighthsignup',
            name='archived_was_absent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicaleighthsignup',
            name='pass_accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicaleighthsignup',
            name='was_absent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
