# Generated by Django 2.2.13 on 2020-12-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0062_auto_20200116_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eighthactivity',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='room_activity_set', to='eighth.EighthRoom'),
        ),
    ]
