# Generated by Django 2.2.18 on 2021-02-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0063_auto_20201224_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eighthactivity',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='eighth.EighthRoom'),
        ),
    ]
