# Generated by Django 3.2.15 on 2022-09-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0064_auto_20210205_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaleighthactivity',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical eighth activity', 'verbose_name_plural': 'historical eighth activities'},
        ),
        migrations.AlterModelOptions(
            name='historicaleighthblock',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical eighth block', 'verbose_name_plural': 'historical eighth blocks'},
        ),
        migrations.AlterModelOptions(
            name='historicaleighthroom',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical eighth room', 'verbose_name_plural': 'historical eighth rooms'},
        ),
        migrations.AlterModelOptions(
            name='historicaleighthscheduledactivity',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical eighth scheduled activity', 'verbose_name_plural': 'historical eighth scheduled activities'},
        ),
        migrations.AlterModelOptions(
            name='historicaleighthsignup',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical eighth signup', 'verbose_name_plural': 'historical eighth signups'},
        ),
        migrations.AlterModelOptions(
            name='historicaleighthsponsor',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical eighth sponsor', 'verbose_name_plural': 'historical eighth sponsors'},
        ),
        migrations.AlterField(
            model_name='historicaleighthactivity',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaleighthblock',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaleighthroom',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaleighthscheduledactivity',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaleighthsignup',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaleighthsponsor',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
