# Generated by Django 3.2.20 on 2024-02-11 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eighth', '0065_auto_20220903_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='eighthactivity',
            name='officers',
            field=models.ManyToManyField(blank=True, related_name='officer_for_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
