# Generated by Django 3.2.25 on 2024-07-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0065_auto_20220903_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='eighthsignup',
            name='absence_notified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='historicaleighthsignup',
            name='absence_notified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
