# Generated by Django 3.2.20 on 2024-02-14 00:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eighth', '0066_eighthactivity_officers'),
    ]

    operations = [
        migrations.AddField(
            model_name='eighthactivity',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_activity_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
