# Generated by Django 3.2.20 on 2024-02-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0067_eighthactivity_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='eighthactivity',
            name='subscriptions_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaleighthactivity',
            name='subscriptions_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
