# Generated by Django 3.2.25 on 2024-03-30 04:11

from django.conf import settings
from django.db import migrations, models
import intranet.utils.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eighth', '0068_auto_20240213_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eighthsponsor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=intranet.utils.deletion.set_historical_user, related_name='sponsor_obj', to=settings.AUTH_USER_MODEL),
        ),
    ]
