# Generated by Django 3.2.25 on 2024-10-12 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eighth', '0070_eighthactivity_club_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='eighthscheduledactivity',
            name='sticky_students',
            field=models.ManyToManyField(blank=True, related_name='sticky_scheduledactivity_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
