# Generated by Django 3.2.25 on 2024-10-11 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0066_auto_20240725_1929'),
        ('eighth', '0070_eighthactivity_club_sponsors'),
    ]

    operations = [
    ]
