# Generated by Django 3.2.25 on 2025-04-29 15:28

from django.db import migrations, models
import intranet.apps.eighth.models

def generate_attendance_codes(apps, schema_editor):
    EighthScheduledActivity = apps.get_model('eighth', 'EighthScheduledActivity')
    HistoricalEighthScheduledActivity = apps.get_model('eighth', 'HistoricalEighthScheduledActivity')
    
    for activity in EighthScheduledActivity.objects.all():
        activity.attendance_code = intranet.apps.eighth.models.EighthScheduledActivity.random_code()
        activity.save(update_fields=['attendance_code'])
    
    for historical_activity in HistoricalEighthScheduledActivity.objects.all():
        historical_activity.attendance_code = intranet.apps.eighth.models.EighthScheduledActivity.random_code()
        historical_activity.save(update_fields=['attendance_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0071_eighthscheduledactivity_sticky_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='eighthscheduledactivity',
            name='attendance_code',
            field=models.CharField(default=intranet.apps.eighth.models.random_code, max_length=6),
        ),
        migrations.AddField(
            model_name='historicaleighthscheduledactivity',
            name='attendance_code',
            field=models.CharField(default=intranet.apps.eighth.models.random_code, max_length=6),
        ),
        migrations.RunPython(generate_attendance_codes, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='eighthscheduledactivity',
            name='code_mode',
            field=models.IntegerField(choices=[(0, 'Auto'), (1, 'Open'), (2, 'Closed')], default=0),
        ),
        migrations.AddField(
            model_name='historicaleighthscheduledactivity',
            name='code_mode',
            field=models.IntegerField(choices=[(0, 'Auto'), (1, 'Open'), (2, 'Closed')], default=0),
        ),
    ]
