# Generated by Django 5.2.4 on 2025-07-13 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0071_eighthscheduledactivity_sticky_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eighthscheduledactivity',
            name='waitlist',
            field=models.ManyToManyField(related_name='%(class)s_scheduledactivity_set', through='eighth.EighthWaitlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
