# Generated by Django 5.2.8 on 2025-12-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eighth", "0072_alter_eighthscheduledactivity_waitlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="eighthscheduledactivity",
            name="hidden_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaleighthscheduledactivity",
            name="hidden_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
