# Stubs for unittest (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .result import TestResult as TestResult
from .case import TestCase as TestCase, FunctionTestCase as FunctionTestCase, SkipTest as SkipTest, skip as skip, skipIf as skipIf, skipUnless as skipUnless, expectedFailure as expectedFailure
from .suite import TestSuite as TestSuite
from .loader import TestLoader as TestLoader, defaultTestLoader as defaultTestLoader, makeSuite as makeSuite, getTestCaseNames as getTestCaseNames, findTestCases as findTestCases
from .runner import TextTestRunner as TextTestRunner, TextTestResult as TextTestResult
from .signals import installHandler as installHandler, registerResult as registerResult, removeResult as removeResult, removeHandler as removeHandler
