class CreateModel:
  # FIXME: actually figure out args
  def __init__(self, **kwargs): ...
class Migration: ...
class AlterModelOptions:
  # FIXME: actually figure out args
  def __init__(self, **kwargs): ...
class AlterUniqueTogether:
  # FIXME: actually figure out args
  def __init__(self, **kwargs): ...
class AlterModelManagers:
  # FIXME: actually figure out args
  def __init__(self, **kwargs): ...
class AlterField:
  # FIXME: actually figure out args
  def __init__(self, **kwargs): ...
class RenameField:
  # FIXME: actually figure out args
  def __init__(self, **kwargs): ...
class AddField:
  # FIXME: actually figure out args
  def __init__(self, **kwargs): ...
