class CreateModel:
  # FIXME: actually figure out args
  def __init__(self, **kwargs): ...
class DeleteModel:
  # FIXME: actually figure out args
  def __init__(self, **kwargs): ...
class Migration: ...
class AlterModelOptions:
  # FIXME: actually figure out args
  def __init__(self, **kwargs): ...
class AlterUniqueTogether:
  # FIXME: actually figure out args
  def __init__(self, **kwargs): ...
class AlterModelManagers:
  # FIXME: actually figure out args
  def __init__(self, **kwargs): ...
class Field:
  # FIXME: actually figure out args
  def __init__(self, **kwargs): ...
class AlterField(Field): ...
class RenameField(Field): ...
class AddField(Field): ...
class RemoveField(Field): ...
def swappable_dependency(*args): ...  # FIXME: figure out args
