class RenameModel:
  def __init__(self, **kwargs): ...
class CreateModel:
  def __init__(self, **kwargs): ...
class DeleteModel:
  def __init__(self, **kwargs): ...
class Migration: ...
class AlterModelOptions:
  def __init__(self, **kwargs): ...
class AlterUniqueTogether:
  def __init__(self, **kwargs): ...
class AlterModelManagers:
  def __init__(self, **kwargs): ...
class Field:
  def __init__(self, **kwargs): ...
class AlterField(Field): ...
class RenameField(Field): ...
class AddField(Field): ...
class RemoveField(Field): ...
def swappable_dependency(*args): ...
