class Field:
  # FIXME: actually figure out args
  def __init__(self, *args, **kwargs): ...
class AutoField(Field): ...
class CharField(Field): ...
class BooleanField(Field): ...
class ManyToManyField(Field): ...
class IntegerField(Field): ...
class DateField(Field): ...
class ForeignKey:
  # FIXME: actually figure out args
  def __init__(self, *args, **kwargs): ...
class Model: ...
class Manager:
  def all(self): ...
