# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('events', '0015_auto_20151130_1427')]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_time',
            new_name='added',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='last_modified_time',
            new_name='updated',
        ),
    ]
