# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 03:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0016_auto_20160323_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUserMap',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'))],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['time']},
        ),
        migrations.AddField(
            model_name='eventusermap',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_user_map', to='events.Event'),
        ),
        migrations.AddField(
            model_name='eventusermap',
            name='users_hidden',
            field=models.ManyToManyField(blank=True, related_name='events_hidden', to=settings.AUTH_USER_MODEL),
        ),
    ]
