# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('events', '0017_auto_20160323_2305')]

    operations = [migrations.AddField(
        model_name='event',
        name='show_on_dashboard',
        field=models.BooleanField(default=True),
    )]
