# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_event_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('school', 'In School'), ('sports', 'Sports')], default='school', max_length=6),
        ),
    ]
