# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('events', '0024_auto_20170307_2037'), ('events', '0025_auto_20170307_2040')]

    dependencies = [
        ('events', '0023_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Show Event on Dashboard'),
        ),
        migrations.AlterField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Show on Login Page'),
        ),
    ]
