# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('printing', '0006_printjob_page_range')]

    operations = [migrations.AddField(
        model_name='printjob',
        name='duplex',
        field=models.BooleanField(default=True),
    )]
