# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('printing', '0008_auto_20160828_2058')]

    operations = [migrations.AddField(model_name='printjob', name='fit', field=models.BooleanField(default=False, verbose_name='Fit-to-page'))]
