# Generated by Django 3.2.20 on 2023-11-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0009_printjob_fit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='duplex',
            field=models.BooleanField(default=True, verbose_name='Double-sided'),
        ),
    ]
