# Generated by Django 5.2.11 on 2026-05-24 18:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0010_alter_printjob_duplex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingInfraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('active_until', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printing_infractions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='PrintingBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('ban_reason_type', models.CharField(choices=[('auto', 'Automatic (infraction threshold)'), ('manual', 'Manual (admin issued)')], default='manual', max_length=10)),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printing_bans', to=settings.AUTH_USER_MODEL)),
                ('triggering_infractions', models.ManyToManyField(blank=True, to='printing.printinginfraction')),
            ],
            options={
                'ordering': ['-date_issued'],
            },
        ),
    ]
