# Generated by Django 3.2.25 on 2024-07-24 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0007_auto_20151221_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPushNotificationPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eighth_reminder_notifications', models.BooleanField(default=True, verbose_name='Eighth Period Reminder Notifications')),
                ('eighth_waitlist_notifications', models.BooleanField(default=False, verbose_name='Eighth Period Waitlist Notifications')),
                ('glance_notifications', models.BooleanField(default=False, verbose_name='Eighth Period Glance Notification')),
                ('announcement_notifications', models.BooleanField(default=True, verbose_name='Announcement Notifications')),
                ('poll_notifications', models.BooleanField(default=True, verbose_name='Poll Notifications')),
                ('silent_notifications', models.BooleanField(default=False, verbose_name='Silent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
