# Generated by Django 3.2.25 on 2024-07-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_userpushnotificationpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpushnotificationpreferences',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
