# Generated by Django 3.2.25 on 2024-07-25 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_userpushnotificationpreferences_is_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpushnotificationpreferences',
            name='silent_notifications',
        ),
    ]
