# Generated by Django 3.2.25 on 2024-07-30 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('push_notifications', '0010_alter_gcmdevice_options_and_more'),
        ('notifications', '0011_webpushnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpushnotificationpreferences',
            name='bus_notifications',
            field=models.BooleanField(default=False, verbose_name='Bus Notifications'),
        ),
        migrations.AlterField(
            model_name='webpushnotification',
            name='device_sent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_device_sent', to='push_notifications.webpushdevice'),
        ),
        migrations.AlterField(
            model_name='webpushnotification',
            name='user_sent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_user_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
