# Generated by Django 3.2.25 on 2024-08-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_auto_20240730_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpushnotificationpreferences',
            name='bus_notifications',
            field=models.BooleanField(default=True, verbose_name='Bus Notifications'),
        ),
        migrations.AlterField(
            model_name='userpushnotificationpreferences',
            name='eighth_waitlist_notifications',
            field=models.BooleanField(default=True, verbose_name='Eighth Period Waitlist Notifications'),
        ),
        migrations.AlterField(
            model_name='userpushnotificationpreferences',
            name='glance_notifications',
            field=models.BooleanField(default=True, verbose_name='Eighth Period Glance Notification'),
        ),
    ]
