# Stubs for django.forms (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.


from django.forms.boundfield import *
from django.forms.fields import *
from django.forms.forms import *
from django.forms.formsets import *
from django.forms.models import *
from django.forms.widgets import *

class Form(BaseForm): ...
