# Stubs for simple_history.middleware (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .models import HistoricalRecords as HistoricalRecords

class HistoryRequestMiddleware:
    def process_request(self, request): ...
    def process_response(self, request, response): ...
