# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=30)),
                ('bus_number', models.CharField(blank=True, max_length=5)),
                ('status',
                 models.CharField(choices=[('a', 'Arrived (In the lot)'), ('d', 'Delayed'), ('o', 'On Time (Expected)')], max_length=1,
                                  verbose_name='arrival status')),
            ],
        ),
    ]
