# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('a', 'Arrived (In the lot)'), ('d', 'Delayed'), ('o', 'On Time (Expected)')], default='o', max_length=1,
                                   verbose_name='arrival status'),
        ),
    ]
