# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-02 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20170606_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='space',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
