# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_route_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
