# Generated by Django 3.2.17 on 2023-02-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_busannouncement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busannouncement',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='busannouncement',
            name='active',
        ),
    ]
