# Generated by Django 3.2.17 on 2023-03-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_auto_20230221_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busannouncement',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
