# Generated by Django 3.2.25 on 2026-01-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_alter_busannouncement_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='reason',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='route',
            name='estimated_time_delay',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
