# Generated by Django 3.2.25 on 2025-05-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_alter_busannouncement_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=10)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
