# Generated by Django 3.2.25 on 2025-05-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0009_busdelay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusDelay',
        ),
        migrations.AddField(
            model_name='route',
            name='reason',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
