# Generated by Django 3.2.25 on 2025-05-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0010_auto_20250520_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='estimated_time_delay',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
