# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('itemreg', '0002_auto_20160409_2157')]

    operations = [
        migrations.AlterField(
            model_name='computerregistration',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='phoneregistration',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
