# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('itemreg', '0003_auto_20160409_2240')]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='retrieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='found',
            field=models.BooleanField(default=False),
        ),
    ]
