# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('itemreg', '0006_auto_20160410_2215')]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='user',
        ),
        migrations.DeleteModel(name='FoundItem',),
        migrations.DeleteModel(name='LostItem',),
    ]
