# Generated by Django 2.2.13 on 2021-01-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemreg', '0009_auto_20180524_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneregistration',
            old_name='serial',
            new_name='imei',
        ),
    ]
