# Stubs for django.utils.deprecation (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class RemovedInDjango20Warning(PendingDeprecationWarning): ...
class RemovedInDjango110Warning(DeprecationWarning): ...

RemovedInNextVersionWarning = ... # type: Any

class warn_about_renamed_method:
    class_name = ... # type: Any
    old_method_name = ... # type: Any
    new_method_name = ... # type: Any
    deprecation_warning = ... # type: Any
    def __init__(self, class_name, old_method_name, new_method_name, deprecation_warning): ...
    def __call__(self, f): ...

class RenameMethodsBase(type):
    renamed_methods = ... # type: Any
    def __new__(cls, name, bases, attrs): ...

class DeprecationInstanceCheck(type):
    def __instancecheck__(self, instance): ...
