# Stubs for oauth2_provider (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

default_app_config = ...  # type: Any
VERSION = ...  # type: Any
