# Stubs for oauth2_provider.middleware (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class OAuth2TokenMiddleware:
    def process_request(self, request): ...
    def process_response(self, request, response): ...
