class HttpResponse:
  # FIXME: figure out args
  def __init__(self, *args, **kwargs): ...
class StreamingHttpResponse(HttpResponse): ...
class Http404:
  # FIXME: figure out args
  def __init__(self, *args, **kwargs): ...
