class HttpResponse:
  # FIXME: figure out args
  def __init__(self, *args, **kwargs): ...
class JsonResponse: ...
class StreamingHttpResponse(HttpResponse): ...
class HttpResponseRedirect: ...
class Http404:
  # FIXME: figure out args
  def __init__(self, *args, **kwargs): ...
