# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('ionldap', '0003_auto_20160205_2210')]

    operations = [migrations.AlterField(model_name='ldapcourse', name='course_id', field=models.CharField(max_length=10),)]
