# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ionldap', '0004_auto_20160205_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ldapcourse',
            options={'ordering': ('period', 'end_period')},
        ),
    ]
