# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20160330_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='safe_html',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardpostcomment',
            name='safe_html',
            field=models.BooleanField(default=False),
        ),
    ]
