# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import intranet.utils.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20160828_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=intranet.utils.deletion.SET_HISTORICAL_USER, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boardpostcomment',
            name='user',
            field=models.ForeignKey(on_delete=intranet.utils.deletion.SET_HISTORICAL_USER, to=settings.AUTH_USER_MODEL),
        ),
    ]
