class MigrationMock: ...
class InvalidString(str): ...
class GlobList:
  def __init__(self, ips: List[str]) -> None: ...
def parse_db_url(db_url: str) -> Dict[str,str]: ...
def get_current_commit_short_hash(workdir: str) -> str: ...
def get_current_commit_long_hash(workdir: str) -> str: ...
def get_current_commit_info() -> str: ...
def get_current_commit_date() -> str: ...
def get_current_commit_github_url(workdir: str) -> str: ...
