# Generated by Django 3.2.18 on 2023-06-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0024_auto_20161004_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('content', models.TextField(help_text='Content of the warning. You can use HTML here.')),
            ],
        ),
    ]
