# Generated by Django 3.2.18 on 2023-06-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0025_warningannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='warningannouncement',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether or not to show the warning.'),
        ),
    ]
