# Generated by Django 3.2.18 on 2023-06-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0027_auto_20230601_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='warningannouncement',
            name='type',
            field=models.CharField(choices=[('global', 'Global Warning (displays on all pages)'), ('dashboard', 'Dashboard Warning (displays on dashboard)')], default='dashboard', max_length=31),
            preserve_default=False,
        ),
    ]
