# Generated by Django 3.2.17 on 2023-06-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0030_alter_warningannouncement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warningannouncement',
            name='type',
            field=models.CharField(choices=[('dashboard', 'Dashboard Warning (displays on dashboard)'), ('global', 'Global Warning (displays on all pages)'), ('dashboard_login', 'Dashboard and Login Warning (displays on dashboard and login pages)'), ('login', 'Login Warning (displays on login page)')], default='dashboard', max_length=127),
        ),
    ]
