# Generated by Django 3.2.20 on 2024-02-14 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eighth', '0067_eighthactivity_subscribers'),
        ('announcements', '0032_alter_warningannouncement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eighth.eighthactivity'),
        ),
    ]
