# Generated by Django 3.2.25 on 2025-02-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0034_historicalannouncement_historicalwarningannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='public',
            field=models.BooleanField(default=False, help_text='Whether to show the announcement, even if the club is restricted (club announcements only)'),
        ),
        migrations.AddField(
            model_name='historicalannouncement',
            name='public',
            field=models.BooleanField(default=False, help_text='Whether to show the announcement, even if the club is restricted (club announcements only)'),
        ),
    ]
