# Generated by Django 3.2.25 on 2025-11-30 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0036_auto_20250415_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementrequest',
            name='teachers_rejected',
            field=models.ManyToManyField(blank=True, related_name='teachers_rejected', to=settings.AUTH_USER_MODEL),
        ),
    ]
