# Generated by Django 3.2.25 on 2025-05-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0036_auto_20250415_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementrequest',
            name='atleast_one_approved',
            field=models.BooleanField(default=False),
        ),
    ]
