# Generated by Django 5.2.4 on 2026-02-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0037_announcementrequest_teachers_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwarningannouncement',
            name='type',
            field=models.CharField(choices=[('dashboard', 'Dashboard Warning (displays on dashboard)'), ('login', 'Login Warning (displays on login page)'), ('dashboard_login', 'Dashboard and Login Warning (displays on dashboard and login pages)'), ('global', 'Global Warning (displays on all pages)'), ('printing', 'Printing Warning (displays on printing page)')], default='dashboard', max_length=127),
        ),
        migrations.AlterField(
            model_name='warningannouncement',
            name='type',
            field=models.CharField(choices=[('dashboard', 'Dashboard Warning (displays on dashboard)'), ('login', 'Login Warning (displays on login page)'), ('dashboard_login', 'Dashboard and Login Warning (displays on dashboard and login pages)'), ('global', 'Global Warning (displays on all pages)'), ('printing', 'Printing Warning (displays on printing page)')], default='dashboard', max_length=127),
        ),
    ]
