# Generated by Django 3.2.25 on 2025-05-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0037_announcementrequest_atleast_one_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementrequest',
            name='atleast_one_approved',
        ),
    ]
