# Stubs for fabric.api (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from fabric.context_managers import hide, settings, show, path, prefix, lcd, quiet, warn_only, remote_tunnel, shell_env
from fabric.operations import require, prompt, put, get, run, sudo, local
from fabric.state import env, output
from fabric.utils import abort, warn, puts, fastprint
