# Stubs for fabric.state (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

win32 = ...  # type: Any
default_port = ...  # type: str
default_ssh_config_path = ...  # type: Any
env_options = ...  # type: Any
env = ...  # type: Any
exceptions = ...  # type: Any
exception_dict = ...  # type: Any
commands = ...  # type: Any
connections = ...  # type: Any

def default_channel(): ...

output = ...  # type: Any
