# Generated by Django 3.2.18 on 2023-06-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20230613_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
