# Generated by Django 3.2.18 on 2023-06-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_request_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
