# Generated by Django 3.2.18 on 2023-06-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_request_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
