# Generated by Django 3.2.18 on 2023-07-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_request_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='ip',
            field=models.TextField(verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='request',
            name='method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_agent',
            field=models.TextField(),
        ),
    ]
