# Stubs for dateutil.relativedelta (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class weekday:
    weekday = ...  # type: Any
    n = ...  # type: Any
    def __init__(self, weekday, n=None): ...
    def __call__(self, n): ...
    def __eq__(self, other): ...

MO = ...  # type: Any
TU = ...  # type: Any
WE = ...  # type: Any
TH = ...  # type: Any
FR = ...  # type: Any
SA = ...  # type: Any
SU = ...  # type: Any

class relativedelta:
    years = ...  # type: Any
    months = ...  # type: Any
    days = ...  # type: Any
    leapdays = ...  # type: Any
    hours = ...  # type: Any
    minutes = ...  # type: Any
    seconds = ...  # type: Any
    microseconds = ...  # type: Any
    year = ...  # type: Any
    month = ...  # type: Any
    day = ...  # type: Any
    weekday = ...  # type: Any
    hour = ...  # type: Any
    minute = ...  # type: Any
    second = ...  # type: Any
    microsecond = ...  # type: Any
    def __init__(self, dt1=None, dt2=None, years=0, months=0, days=0, leapdays=0, weeks=0, hours=0, minutes=0, seconds=0, microseconds=0, year=None, month=None, day=None, weekday=None, yearday=None, nlyearday=None, hour=None, minute=None, second=None, microsecond=None): ...
    @property
    def weeks(self): ...
    @weeks.setter
    def weeks(self, value): ...
    def normalized(self): ...
    def __add__(self, other): ...
    def __radd__(self, other): ...
    def __rsub__(self, other): ...
    def __sub__(self, other): ...
    def __neg__(self): ...
    def __bool__(self): ...
    __nonzero__ = ...  # type: Any
    def __mul__(self, other): ...
    __rmul__ = ...  # type: Any
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __div__(self, other): ...
    __truediv__ = ...  # type: Any
