# Stubs for oauth2_provider.views.application (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.views.generic import CreateView, DetailView, DeleteView, ListView, UpdateView
from braces.views import LoginRequiredMixin
from ..models import get_application_model as get_application_model

class ApplicationOwnerIsUserMixin(LoginRequiredMixin):
    fields = ...  # type: str
    def get_queryset(self): ...

class ApplicationRegistration(LoginRequiredMixin, CreateView):
    template_name = ...  # type: str
    def get_form_class(self): ...
    def form_valid(self, form): ...

class ApplicationDetail(ApplicationOwnerIsUserMixin, DetailView):
    context_object_name = ...  # type: str
    template_name = ...  # type: str

class ApplicationList(ApplicationOwnerIsUserMixin, ListView):
    context_object_name = ...  # type: str
    template_name = ...  # type: str

class ApplicationDelete(ApplicationOwnerIsUserMixin, DeleteView):
    context_object_name = ...  # type: str
    success_url = ...  # type: Any
    template_name = ...  # type: str

class ApplicationUpdate(ApplicationOwnerIsUserMixin, UpdateView):
    context_object_name = ...  # type: str
    template_name = ...  # type: str
