# Stubs for oauth2_provider.views.application (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.views.generic.base import View

class ApplicationUpdate(View):
    context_object_name = ...  # type: str
    template_name = ...  # type: str
