# Stubs for pip.req.req_file (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def parse_requirements(filename, finder: Optional[Any] = ..., comes_from: Optional[Any] = ..., options: Optional[Any] = ..., session: Optional[Any] = ..., constraint: bool = ..., wheel_cache: Optional[Any] = ...): ...
